# All the Ruby Galaxy Hosts

daniel_kim:
    name: Daniel Kim
    twitter: http://twitter.com/learnwdaniel

danny_ramos:
    name: Danny Ramos
    email: dramos@newrelic.com
    headshot: /assets/img/Danny_headshot.png
    linkedin: https://www.linkedin.com/in/danny-ramos-j/
    twitch: https://twitch.tv/muydanny
    twitter: http://twitter.com/muydanny
    github: https://github.com/muydanny
    bio: Danny Ramos is a Developer Relations Engineer at New Relic. Having spent the majority of his life in the creative arts, Danny highly values connecting and sharing experiences with other people. From grinding as a janitor to putting in 70-hour weeks as a software development student, he’s no stranger to getting his hands dirty in the pursuit of his goals.

jonan_scheffler:
    name: Jonan Scheffler
    email: johndoe@email.com
    headshot: /assets/img/Jonan_headshot.jpg
    twitch: https://twitch.tv/thejonanshow
    twitter: http://twitter.com/thejonanshow
    github: https://github.com/thejonanshow
    bio: Jonan is the Director of Developer Relations at New Relic and an aspiring astronaut. He believes in you and your potential and wants to help you build beautiful things.

mayra_navarro:
    name: Mayra Navarro
    twitter: https://twitter.com/mayralunavarro/media

rachael_wright_munn:
    name: Rachael Wright-Munn
    email: chaelcodes@gmail.com
    headshot: /assets/img/Rachael_headshot.jpg
    linkedin: https://www.linkedin.com/in/rachael-wright-chaelcodes/
    twitch: https://twitch.tv/ChaelCodes
    twitter: http://twitter.com/chaelcodes
    github: https://github.com/chaelcodes
    web: https://www.chael.codes
    bio: Rachael wants to share the joy and beauty of programming through programming games and regular open-source streams on Twitch. She's been a professional dev since 2012, 3x Team Lead, and manages an open-source repo for playing games of Monster of the Week. Currently, she works as a Developer Relations Engineer for New Relic.
